# Discussion and Recommendations

## Weigert Creek - PSCIS crossing 197534
Fish were captured upstream of the highway only to within the first two reaches to within 300m upstream of the first ford on the Weigert Creek FSR that is located at an elevation of 1320m approximately 1.5km above Highway 43.  Above this location, although significant electrofishing effort was conducted at a location approximately 2.5km upstream of the highway within Reach 3 and at a site located approximately 6km upstream of the highway within Reach 4, no fish were captured. In the fall of 2022 the entire channel width within Reach 5 was dewatered at a location approximately 8km upstream of Highway 43. 

<br>

Although physical habitat characteristics (pool depths, presence of gravels/LWD, etc) appeared suitable to support westslope cutthrout trout in Reach 3 approximately 5km upstream of Highway 43 and in fact had more complexity than lower reaches due to large woody debris abundance and percent composition of pools, there were no fish captured in the area sampled. This was not expected, as the entire section of stream between where was sampled in Reach 3 and where fish were captured in Reach 2 was surveyed and although some smaller large woody debris jams from 60 - 70cm were observed, no permanent barriers were present that we would expect to block upstream migration of adult westslope cutthrout trout. 

<br>

Cold water temperatures have been demonstrated to provide recruitment bottlenecks in early life stages of westslope cutthrout trout with days during the growing season above an average of 5$^\circ$C a key determinant in growth and subsequent fry survival during overwintering [@coleman_fausch2007ColdSummera; @coleman_fausch2007ColdSummer]. Furthermore, ongoing programs of temperature modelling for Teck in the region are revealing that the single best predictor variable of westslope cutthrout trout density is temperature (pers. comm. Joe Thorley, Poisson Consulting Ltd.). Although there is some potential that the lack of fish captured in Reach 3 could be related to the potentially hindered upstream migration at the highway culverts, temperature information taken within Reach 1 at approximately 20m upstream of Highway 43 at an elevation of 1260m demonstrated that temperatures close to 5$^\circ$C prevailed at this elevation from May - November 2023 indicating that temperatures at higher elevations in the watershed (ie. Reach 3 begins at 1460m) may preclude fish use of these areas. Research detailed in @coleman_fausch2007ColdSummer  indicates that for translocations of greenback cutthroat trout and Colorado River cutthroat trout in north-central Colorado headwater streams - streams that provide 800–900 degree-days _probably_ sustain recruitment in some years, and report that streams with less than 800 degree-days are generally unsuitable for translocations because of the smaller sizes attained by fry before the onset of winter and the associated greater risk of recruitment failure. 

<br>

Average weekly water temperatures in Weigert Creek were at or above 7$^\circ$C for only four of the 16 week growing season when the temperature logger was present in the stream with a grand total of 693.5 Celsius degree-days estimated from the dataset. Some caution should be applied to the interpretation of this data (because the first week of data collected fell under the average weekly water temperature threshold of 5$^\circ$C and only consisted of three days worth of data - June 24 through June 26) so there is some potential that temperatures in the days and weeks before were high enough that the growing season could be considered longer. However, although subject to change during the drafting of this report (due to ongoing research), at this point in time it seems very conservative to assume that water temperatures were not likely above an average weekly temperature of 5$^\circ$C for more than 5 weeks before temperature logging began. If it is assumed that average temperature was at 5.0$^\circ$C during those 5 extra weeks, the Celsius degree-days would sum to 808.5 which is just barely in the range of _probable_ for sustaining recruitment even at this low elevation in the watershed.  Therefore, cold temperatures during the growing season at locations near the Highway where only adult fish were captured could be an indication that only adult fish are able to survive year to year in these locations as the  570 to 600 Celsius degree days required for fry emergence would leave little time for growth in the system.  This leads us to wonder if fry in these cold systems have evolved to migrate downstream upon emergence seeking warmer rearing temperatures in the first years of life. Although more data is necessary to derive conclusions, this train of thought builds the case that improved passage at the Highway could result in more fish in the areas immediately upstream of the highway as 2+ and 3+ fish may wish to populate these areas if they could access them and currently it seems unlikely that small fish could do so.

<br>

Although difficult to determine cause, presence of only adult fish upstream of the Highway 43 crossing on Weigert Creek and a significant increase in the density of adult fish upstream when compared to downstream could be related to swim speed ability and the associated increased potential for larger fish to migrate from downstream to upstream of the culvert. The fact that fish of the size captured (up to over 30cm long) were within this system so late in the year indicates that they were resident and not merely in the system to spawn.  This is particularly interesting as we would not have expected fish of this size to be resident within a system of this relatively small size (average channel width in Reach 2 of 5.5m).

<br>

Recommendations going forward include:

  * Acquisition of a lidar generated digital elevation model for the a 500m x 500m square area centred over the culvert at Highway 43.  This data can provide insight into historic alignment of the floodplain and past  realignments of the stream due to road infrastructure.  This information can also be extremely valuable for informing future works including not only infrastructure upgrades but restorative actions to increase watershed health.
  
  * To understand current patterns of movement within the stream, conduct electrofishing within currently fish bearing reaches both upstream and downstream of the crossing, pit tag all captured fish (>50mm long) and resample in future years. As there are extensive tagging programs throughout the Elk River watershed including tagging programs conducted by Nupqu as well as numerous guiding companies, this could give an idea of fish movement not only within Weigert Creek but also allow confirmation of habitat use within the mainstem of the Elk River by fish tagged in Weigert Creek as well as of utilization of habitat in Weigert Creek by fish originally tagged in the Elk River.
  

  * Collect Weigert Creek temperature data at points known to support westslope cutthrout trout (ie. immediately upstream of the highway and adjacent to the first ford located approximately 1.5km upstream of Highway 43) as well as at areas further upstream (Reach 3 and Reach 4).  Coordinate with other programs in the watershed to help determine the best locations for loggers, best timing from installation, contribute data to regional databases and leverage/improve temperature modelling in the region. 
  
    * Attempt to predict temperature for the weeks prior to the date that the temperature logger was installed based on modelling aided by data from other water temperatures in area as well as air temperature data taken at these times. 
  
  * To quantify habitat quality further up in the watershed collect more detailed fish habitat information in Reach 3 and Reach 4.
  
  * To build an understanding of spawning cutthrout use and timing within the system conduct redd surveys in the spring/summer.
  
  * To quantify flow characteristics and help build an understanding of how discharge and spawning timing relate to access through the highway crossing, build a stage discharge curve for the watershed and measure flow speeds through the culverts at varying stream discharge rates.


## Brule Creek - PSCIS crossings 197533 and 197559

The waterfall located upstream from Highway 43 limits the amount of potential habitat gained by remediation of stream crossing structures on Busato Road and Highway 43 to 3.6km. Although potentially a result of aggredation related to the Highway 43 culverts and road alignment, the seasonal dewatering  in the first 300 - 500m of habitat immediately upstream of Highway 43 (May 5 - October 15 in 2023) is not a desirable habitat characteristic with potential implications for fish stranding.  However, the presence of numerous mountain whitefish and westslope cutthrout trout holding in outlet pools downstream of both Bosato Road and Highway 43 along with the visual observaton of a fish in a pool upstream of the crossing in 2022 indicate that fish use of the area upstream would likely occur if the culvert barriers are removed. 

<br>

As cold water temperatures could be limiting within stream habitats upstream of the Highway with effects likely increasing in severity with elevation rise, the amount of habitat viable for westslope cutthrout trout may not be any greater (or could in fact be even less) than the 3.6km of habitat present before the falls. 

<br>



Recommendations going forward include:

  * Acquisition of a lidar generated digital elevation model for the a 500m x 500m square area centred over the culvert at Highway 43.  This data can provide insight into historic alignment of the floodplain and past  realignments of the stream due to road infrastructure.  This information can also be extremely valuable for informing future works including not only infrastructure upgrades but restorative actions to increase watershed health.
  
  * Collection of temperature data at points known to support westslope cutthrout trout (ie. within the outlet pools of Bosato Road and Highway 43 culverts) as well as at areas of potential access (below the falls at 3.6km) if fish passage were to be remediated at the sites.

  * Capture and pit tagging of fish holding in the pools below Highway 43 and transplanting to underneath the falls at 3.6km.  Following one or two growing seasons, attempts could be made to recapture these fish from the vicinity of where they have been transplanted.  This would provide valuable insight into fish movement as well as the ability of upstream habitats to support westsloope cutthrout rearing and overwintering.
  
  * Remove the severely damaged Busato Road crossing and restore riparian areas between the two roads to a more functional state would be a cost effective solution to resolve passage into and increase the value of the 125m of habitat located between the two crossings.  Vehicular access to all areas adjacent to Busato Road would not be significantly impacted by removal of the culvert as traffic can access either end of Busato Road from Highway 43.  A stepped approach to restoration on this stream would provide opportunities to understand fish movement and habitat suitability through pit tagging and recapture of fish relocated from areas of construction site salvage to upstream of the Highway as well as downstream of Busato Road. At the time of 2022 surveys, riparian areas between the two roads were heavily degraded and fish passage remediation works at Busato Road would provide opportunities for improvement of soils and riparian vegetation that would have benefits for downstream populations.  In addition, restoration of this first piece of stream would help build momentum for works upstream and build awareness for riparian health issues related to range use of the land adjacent to the stream present on private lands both upstream of Highway 43 and downstream of Busato Road. 
  
  * Quantify habitat quality in the watershed by collecting detailed fish habitat information between the confluence with the Elk River and the falls at 3.6km.



