# Conclusion

Fish passage restoration works at Bittner Creek, Cross Creek and Five Mile Creek demonstrate significant investments in aquatic ecosystem stewardship with benefits apparent at all three sites. Each site provides opportunities to learn from past actions and will help build our state of knowledge going forward. 

<br>


Effectiveness monitoring provides opportunities to collect data on fish populations and their behavior, which can help build the state of knowledge about habitat utilization, health and migration patterns. Additionally, this data can be used to inform future management decisions and planning. Whenever possible, baseline and follow up sampling of fish upstream and downstream of crossings should be conducted. When possible and likely follow up sample timing permits,  Passive Integrated Transponders (PIT tags)  should be inserted into species of interest to track movement and health over time.  If not conducted beforehand, fish salvage during preparation for dewatering before construction could provide opportunities for tagging with minimal costs over and above those already necessary for construction salvage.  This would require collaboration between project managers, consultants conducting salvages and other developers of the overall effectiveness monitoring program but would result in an increase in our state of knowledge of how fish use remediated systems and help standardize effectiveness monitoring protocols. 

<br>

Environmental practitioners, road tenure holders, First Nations, regulators, academia, non-profit organizations, and local stewardship groups must collaborate and invest time to create a comprehensive effectiness monitoring program for fish passage restoration that best benefits stakeholders, fish populations and aquatic ecosystems impacted by infrastructure. This will enable informed decisions, responsible allocation of investments, and ensure the long-term sustainability of fish populations and aquatic ecosystems impacted by linear infrastructure. 

